# This file was generated by GoReleaser. DO NOT EDIT.
# Manual seed for v0.1.0-alpha.1; subsequent tags overwrite via GoReleaser.
cask "doppels" do
  version "0.1.0-alpha.1"

  on_macos do
    on_intel do
      sha256 "c7f56f2297aaebcc57d4db300d0d81df1839f67c304ae3855b4770f33fd674e7"
      url "https://github.com/doppelshq/doppels/releases/download/v#{version}/doppels_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b4db5c7b3ee3f0d1df9b728a5ef930ea18cea6ee0de8dd1d1f158c1287bcedb"
      url "https://github.com/doppelshq/doppels/releases/download/v#{version}/doppels_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9aa651e130386bf459dce1ad2045588167b3cc555c73577146599fa2adefc9d8"
      url "https://github.com/doppelshq/doppels/releases/download/v#{version}/doppels_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d631c4c7ee1ad09039e5854aa8abff5a10626403bfe1f37a880310514853979d"
      url "https://github.com/doppelshq/doppels/releases/download/v#{version}/doppels_#{version}_linux_arm64.tar.gz"
    end
  end

  name "doppels"
  desc "Freeze agent sessions into local deterministic recipes"
  homepage "https://doppels.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doppels"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/doppels"]
    end
  end

  # No zap stanza required
end
